### PR TITLE
[Proposition] GridSearch strategy

### PR DESCRIPTION
**Pull request by kudkudak**
Hello,

I needed to add GridSearch strategy in my case, and I guess in general user might want to go through all the options sometimes. Feel free to close the PR if you don't want to include this :) 

The naming might not be best, as I have to go in a circular fashion through all the options, but I wasn't sure how to name it differently

### CODE REVIEW

**Comment by cxhernandez** [comment]
Thanks! This is a nice addition.

 It'd be nice to also expand this to accept ranges of `float`/`int` variables using the [`jump`](https://github.com/msmbuilder/osprey/blob/a6f1f2edf286b8c55c27f759a5f85e4987b43d09/osprey/search_space.py#L33) search space.

**Comment by kudkudak** [comment]
I think because `add_jump` creates `EnumVariable` it should work "for free" :)

**Comment by cxhernandez** [comment]
> I think because add_jump creates EnumVariable it should work "for free" :)

+1. Could you add it to the test though, as a sanity check?

**Comment by kudkudak** [comment]
Done :)

**Pull request merged**
