### PR TITLE
Fix for #123

### PR DESCRIPTION
**Pull request by kudkudak**
Simple fix for #123 

WIP because I didn't know what to do with internal `_num_samples` in `fit_estimator.py` (there is some custom logic for msmbuilder, which probably should be decoupled, but I am not sure how to do it)

### CODE REVIEW

**Comment by cxhernandez** [comment]
Thanks for the PR! I think the best way to do handle it is to consolidate `fit_estimator._num_samples` into `num_samples`.The `msmbuilder_api` keyword seems to just indicate if the object is a list of lists, so maybe just get rid of it and add a new condition:

```python
if all(isinstance(xx, list) for xx in x):
    return sum(len(xx) for xx in x)
```

**Comment by kudkudak** [comment]
@cxhernandez Thanks, though it is slightly scary, what if the dataset has examples being lists, but the number of samples is actually number of lists? If that' fine, I have updated the PR with the suggested fix :)

**Comment by cxhernandez** [comment]
> Thanks, though it is slightly scary, what if the dataset has examples being lists

Good point! Also, my idea wouldn't work anyways because msmbuilder returns lists of numpy arrays rather than lists of lists (still haven't had my morning coffee :disappointed:)

Perhaps, let's keep the keyword in `num_samples` but pick a better name (e.g. `is_nested`)?

**Comment by kudkudak** [comment]
Cool :) Added `is_nested`

**Comment by cxhernandez** [comment]
Thanks a lot!

**Pull request merged**
