### PR TITLE
keep tests in conda-build

### PR DESCRIPTION
**Pull request by cxhernandez**
re: https://github.com/msmbuilder/osprey/pull/131#issuecomment-204000095

### CODE REVIEW

**Comment by mpharrigan** [comment]
the test command will run in a bespoke conda environment. If `coveralls` needs to be in the source directory, maybe you can keep that in the "after-success" block.

**Comment by mpharrigan** [comment]
p.s. you should be able to try this locally by just running travis's commands

**Comment by mpharrigan** [comment]
Or did it work?

**Comment by cxhernandez** [comment]
travis didn't complain, but I don't think coveralls got the data....

**Comment by cxhernandez** [comment]
> If coveralls needs to be in the source directory, maybe you can keep that in the "after-success" block.

I'll try this, but I'm not sure how it'll find the coverage info from `nose` that way

**Comment by mpharrigan** [comment]
well nose generally needs to be run outside the source directory but coveralls needs to be in the source directory?

**Comment by cxhernandez** [comment]
I think so. The nose test creates `.coverage` so maybe if I move that into the source directory everything will work.

**Comment by cxhernandez** [comment]
@mpharrigan: It works! What do you think?

**Comment by msultan** [comment]
we should put this in msmbuilder too. seems like a fun badge

**Comment by mpharrigan** [comment]
-1 on including in msmbuilder. line-based coverage reports are misleading

**Comment by cxhernandez** [comment]
> line-based coverage reports are misleading

but they kind of game-ify testing :smile:

**Pull request merged**
