### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by mpharrigan**
This ports the msmbuilder (and soon to be mdtraj) doc deployment code. It will actually run the tests on travis and then build the docs. The tests fail as is, and should be updated @cxhernandez 

The docs still need to be updated, and it needs a logo.

The conda recipe updated dependencies should be ported to the omnia conda-recipes, and should be kept up-to-date as the tests get modified.

Osprey was set up to use versioneer, which required writing a shim `version.py` that makes it more similar to msmbuilder and mdtraj [which use a ghetto, roll-your-own versioneer that writes a `version.py` file from `setup.py` based on variables in the latter file. versioneer uses git and tags to figure out the version of stuff]

### CODE REVIEW

**Comment by mpharrigan** [comment]
Hint on fixing tests: you can run conda build locally, which will build and run tests in a pristine conda env automatically

`conda build devtools/conda-recipe`

**Comment by cxhernandez** [comment]
:earth_americas: to @mpharrigan

```
# Move the docs into a versioned subdirectory
python devtools/travis-ci/set_doc_version.py
Traceback (most recent call last):
  File "devtools/travis-ci/set_doc_version.py", line 5, in <module>
    if osprey.release:
NameError: name 'osprey' is not defined
```

**Comment by mpharrigan** [comment]
My versioneer shim to detect whether it's a release or not seems to be broken. We should probably just mothball versioneer and use the msmbuilder/mdtraj strategy of including the version string in setup.py

**Comment by mpharrigan** [comment]
I've removed versioneer and added basesetup.py, which includes a function to write `version.py`. I've also modified the version writing code, and should backport those changes to msmbuilder and mdtraj

**Comment by cxhernandez** [comment]
py27 is missing `requests` still but it looks like it's working otherwise :smile:

**Comment by cxhernandez** [comment]
thanks!

**Comment by mpharrigan** [comment]
Let's see if it works

**Comment by cxhernandez** [comment]
```
missing secret_access_key
failed to deploy
```
Do we add this to Travis?

**Comment by mpharrigan** [comment]
see #113

**Pull request merged**
